### PR TITLE
Catch Missing Data Discrepancies and Throw Warning

### PR DESCRIPTION
**Pull request by rsh52**
# Description
This PR seeks to address a bug where missing data related to the `colour` mapping aesthetic in a given layer will break when an additional layer containing no missing data for that same aes is supplied. To illustrate this better, I am providing a simple `mtcars` example below:

<details>
  <summary>Click me for the code example!</summary>

```r
my_mtcars <- mtcars |>
  dplyr::mutate(
    new_cyl = dplyr::case_when(cyl > 6 ~ NA, TRUE ~ cyl),
    type = dplyr::case_when(mpg >30 ~ "Efficient", 
                            mpg > 20 & mpg <= 30 ~ "Ok Efficiency", 
                            TRUE ~ NA)
  )

mt_p <- ggplot(my_mtcars, aes(x = hp, y = new_cyl)) +
  geom_point(aes(color = type))
mt_p +
  geom_point(data = iris,
             mapping = aes(x = Sepal.Length, y = Sepal.Width, color = Sepal.Width), 
             color = "red")
```

</details>

<details>
  <summary>Click me for the output!</summary>

image

</details>

This code shows a few things that we're trying to allow for in `ggswim`:

- Multiple datasets supplied
- Static and dynamically mapped aesthetic layers

The default behavior of ggplot when a static aesthetic is supplied is to drop the associated mapping aes from the legend. Notice how even though I supplied color to `aes()` in the second `geom_point()` call, the legend doesn't have a red circle for the iris data.

In `ggswim`, we implement a solution to manually capture a statically defined color aesthetic and re-enter it as a mapped one under the hood. This lets us support mapped colours and static ones and have them both appear in the legend. Unfortunately this results in `ggswim` dropping NA data from the legend with no (known) way to re-supply it.

The solution for the time being is to capture the `ggswim` object via the print method with `build_ggswim()` and check if there is a discrepancy between the built legend and what exists in the data itself. If detected, a warning is thrown letting the user know that missing data exists but is not present in the legend: 

```
Warning message:
In build_ggswim(x) :
  ! Missing data detected that has been dropped from the legend display.
ℹ Missing data may still appear in the `ggswim` plot.
```

It would be ideal to re-introduce the missing data back into the legend, but I don't know of any way to do that currently.

# Proposed Changes 
List changes below in bullet format:

- Before applying any `guide()` overrides for the legend via `build_ggswim()`, check for missing data and throw a warning
   - If check detects issue, remove offending override data to negate issue

# Other Things to Consider

Truth be told, I'm not sure how often a user would actually want missing data to appear in their legend as a given marker anyway so I believe this _should_ be very rare and a warning is appropriate (maybe even an error if we think it shouldn't be possible). I can't imagine a time a user would want a gray "NA" for display purposes outside of initial EDA.

### CODE REVIEW

**Comment by rsh52** [comment]
@ddsjoberg Forgot I can't assign you since you're not a member of the org, but curious on your thoughts!

**Comment by ddsjoberg** [comment]
@rsh52 taking the quickest look tonight. I agree that no one needs (and we don't need to support) adding NAs to the legend. With that in mind, can we just use `geom_point(aes(), na.rm = TRUE, ...)` as the default? I'll do a little testing now to see how that goes....

**Comment by rsh52** [comment]
> @rsh52 taking the quickest look tonight. I agree that no one needs (and we don't need to support) adding NAs to the legend. With that in mind, can we just use `geom_point(aes(), na.rm = TRUE, ...)` as the default? I'll do a little testing now to see how that goes....

@ddsjoberg Awesome, if we can agree that enforcing `na.rm = TRUE` is viable then I think I can just nix most of the stuff this PR supplies (I'm not mad about removing code). What happens downstream in `build_ggswim()` is an `override` list gets created that informs `guides()`. Dropping any `NA` values from the `override` responsible for the colour layer will resolve this.

Basically just need this:
`override$colour <- override$colour[!is.na(override$colour$colour_mapping), , drop = FALSE]`

Instead of this and the underlying `check_*` function:
https://github.com/CHOP-CGTInformatics/ggswim/blob/a3f3843eea226ba6ef513cb4d44ea5deb53a1a40/R/build_ggswim.R#L106-L113

**Comment by rsh52** [comment]
I think this is at a good spot now, going to go ahead and merge to main and work on some documentation. Happy enough having this PR to cite in the future should we ever need to come back to the rationale for why `NA` data is problematic.

**Pull request merged**
